dist: trusty
language: go
#go_import_path: github.com/opensds/opensds
sudo: required

go:
  - 1.7
  - 1.8
  - tip

env:
  matrix:
   - TARGET=amd64
   - TARGET=arm64
   - TARGET=arm
   - TARGET=386
   - TARGET=ppc64le

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
  - go: tip
    env: TARGET=arm
  - go: tip
    env: TARGET=arm64
  - go: tip
    env: TARGET=386
  - go: tip
    env: TARGET=ppc64le

before_install:
  - ssh-keygen -f $HOME/.ssh/id_rsa -t rsa -N ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod 600 ~/.ssh/authorized_keys
  - sudo pip install ceph-deploy
  - ceph-deploy install --release giant `hostname`
  - ceph-deploy pkg --install librados-dev `hostname`
  - ceph-deploy pkg --install librbd-dev `hostname`
  - ceph-deploy pkg --install libcephfs-dev `hostname`
  - bash ci/micro-osd.sh /tmp/micro-ceph
  - export CEPH_CONF=/tmp/micro-ceph/ceph.conf
  - ceph status

#script:
# - >
#    case "${TARGET}" in
#      amd64)
#        GOARCH=amd64 ./test
#        ;;
#      386)
#        GOARCH=386 PASSES="build unit" ./test
#        ;;
#      *)
#        # test building out of gopath
#        GO_BUILD_FLAGS="-a -v" GOPATH="" GOARCH="${TARGET}" ./build
#        ;;
#    esac
