---
- name: kill etcd daemon service
  shell: killall etcd
  ignore_errors: yes
  when: db_driver == "etcd"

- name: remove etcd service data
  file:
    path: "{{ etcd_dir }}"
    state: absent
    force: yes
  ignore_errors: yes
  when: db_driver == "etcd"

- name: remove etcd tarball
  file:
    path: "/tmp/{{ etcd_tarball }}"
    state: absent
    force: yes
  ignore_errors: yes
  when: db_driver == "etcd"

- name: kill osdslet daemon service
  shell: killall osdslet
  ignore_errors: yes

- name: kill osdsdock daemon service
  shell: killall osdsdock
  ignore_errors: yes

- name: clean all opensds build files
  file:
    path: "{{ opensds_build_dir }}"
    state: absent
    force: yes
  ignore_errors: yes

- name: clean all opensds configuration files
  file:
    path: "{{ opensds_config_dir }}"
    state: absent
    force: yes
  ignore_errors: yes

- name: clean all opensds log files
  file:
    path: "{{ opensds_log_dir }}"
    state: absent
    force: yes
  ignore_errors: yes

- name: check if it existed before cleaning a volume group
  shell: vgdisplay {{ vg_name }}
  ignore_errors: yes
  register: vg_existed
  when: enabled_backend == "lvm"

- name: remove a volume group if lvm backend specified
  shell: vgremove {{ vg_name }}
  when: enabled_backend == "lvm" and vg_existed.rc == 0

- name: check if it existed before cleaning a physical volume
  shell: pvdisplay {{ pv_device }}
  ignore_errors: yes
  register: pv_existed
  when: enabled_backend == "lvm"

- name: remove a physical volume if lvm backend specified
  shell: pvremove {{ pv_device }}
  when: enabled_backend == "lvm" and pv_existed.rc == 0

- name: stop cinder-standalone service
  shell: docker-compose down
  become: true
  args:
    chdir: /root/cinder/contrib/block-box
  when: enabled_backend == "cinder"

#- name: purge ceph cluster if ceph backend specified
#  shell: ansible-playbook purge-cluster.yml -i ceph.hosts
#  become: true
#  args:
#    chdir: /tmp/ceph-ansible/infrastructure-playbooks
#  when: enabled_backend == "ceph"

#- name: remove ceph-ansible source code
#  file:
#    path: /tmp/ceph-ansible
#    state: absent
#    force: yes
#  ignore_errors: yes
#  when: enabled_backend == "ceph"
